
module.exports = {
  testEnvironment: 'node',
  setupFilesAfterEnv: ['./jest.setup.js'],
  testMatch: [
    '**/test_app.js',
    '**/test_fm_storage.js',
    '**/test_fm_identity.js',
    '**/test_server_api.js',
    '**/test_trust_bar.js',
    '**/test_first_scan.js',
    '**/test_shopper.js',
    '**/test_coach_plan.js',
    '**/test_sanitize_plan.js',
    '**/test_seo_ship_pack_1.js',
    '**/test_seo_pack_2.js',
    '**/test_coach_landers.js',
    '**/test_seo_pack_3.js',
    '**/test_public_price_ban.js',
    '**/test_pay_path.js',
    '**/test_funnel_events.js',
    '**/test_checkout_duplicates.js',
    '**/test_coach_billing.js',
    '**/test_comp_expiry.js',
    '**/test_ios_store_art.js',
    '**/test_pre_asc_gate.js',
    '**/test_ai_client.js',
    '**/test_server_ai.js',
    '**/test_alert_5xx.js',
    '**/test_web_analytics.js',
    '**/test_smoke_checkout.js',
    '**/test_smoke_prod.js',
    '**/test_vercel_deploy_ops.js',
    '**/test_prod_smoke_job.js',
    '**/test_prod_incident.js',
  ],
  testPathIgnorePatterns: ['/node_modules/', '/dist/'],
  collectCoverage: true,
  collectCoverageFrom: [
    'public/script.js',
    'public/js/fm-storage.js',
    'public/js/fm-identity.js',
    'grok_agent.js',
    'grok_assistant.js'
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov'],
  verbose: true,
  testTimeout: 10000,
  moduleFileExtensions: ['js', 'json', 'jsx'],
  globals: {
    'ts-jest': {
      useESM: true,
    },
  },
  transform: {}
};
